import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/src/components/Navbar"; // adjust path to where your Navbar lives
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Uni Meetup",
  description: "Generated by create next app",
  // Corrected icon metadata structure
  icons: {
    icon: "/favicon.ico", // Or "/logo.svg" depending on your icon name
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
      <body className="min-h-screen flex flex-col bg-white text-black">
        <Navbar />
        {/* main wrapper to push the footer down if you add one later */}
        <main className="flex-grow">
          {children}
        </main>
      </body>
    </html>
  );
}